kr120r2700:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint1_position_controller:
    type: effort_controller/JointPositionController
    joint: base_link__link1
    pid: {p: 700, i: 50, d: 70}

  joint2_position_controller:
    type: effort_controller/JointPositionController
    joint: link1__link2
    pid: {p: 700, i: 50, d: 70}
  
  joint3_position_controller:
    type: effort_controller/JointPositionController
    joint: link2__link3
    pid: {p: 700, i: 50, d: 70}

  joint4_position_controller:
    type: effort_controller/JointPositionController
    joint: link3__link4
    pid: {p: 700, i: 50, d: 70}

  joint5_position_controller:
    type: effort_controller/JointPositionController
    joint: link4__link5
    pid: {p: 700, i: 50, d: 70}

  joint6_position_controller:
    type: effort_controller/JointPositionController
    joint: link5__flange
    pid: {p: 700, i: 50, d: 70}
